name: Compilar Chatwoot Modificado

on:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compilar y Subir Imagen Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: docker/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/chatwoot-afs:latest
